version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    user: root
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=admin123
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins/casc_configs:/var/jenkins_home/casc_configs
    networks:
      - jenkins-net

volumes:
  jenkins_home:

networks:
  jenkins-net:
