jobs:
  - script: >
      folder('POC3') {
        displayName('POC3')
        description('Folder for Proof of Concept jobs')
      }

      pipelineJob('POC3/DemoPipeline2') {
        description('POC mock pipeline job for testing JCasC + Job DSL')
        definition {
          cps {
            script('''\
              pipeline {
                agent any
                stages {
                  stage('Init') {
                    steps {
                      echo 'Preparing environment...'
                    }
                  }
                  stage('Build') {
                    steps {
                      echo 'Running mock build...'
                    }
                  }
                  stage('Test') {
                    steps {
                      echo 'Executing mock tests...'
                    }
                  }
                }
              }
            '''.stripIndent())
            sandbox(true)
          }
        }
        disabled(false)
      }